name: nonlinear_programming
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy.optimize
  - scipy.optimize.minimize
  - scipy.optimize.NonlinearConstraint
  - plotly.graph_objects
  - autograd.numpy
  - autograd.grad
  - time.time
  - random.uniform